### ISSUE TITLE
WaitForEvent should return an exit code

### ISSUE THREAD

**Issue by mrb113** [southpolenator/WinDbgCs#29]
When using the DbgEng library to get direct access to the debugging APIs, I expect WaitForEvent to return an exit code. However, it returns void.

See the original documentation on WaitForEvent:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dbgeng/nf-dbgeng-idebugcontrol-waitforevent

Return code | Description
-- | --
S_OK | The method was successful.
S_FALSE | The time-out expired.
E_PENDING | An exit interrupt was issued.  The target is not available.
E_UNEXPECTED | Either there is an outstanding request for input, or none of the targets could generate events.
E_FAIL | The engine is already waiting for an event.

I want to take some action based on whether or not WaitForEvent timed out, which is possible with the original API. With WinDbgCS, I need to roll my own mechanism to figure out whether we timed out.

**Comment by southpolenator** [comment]
Oh, I see, so you want to get S_FALSE function result... I wanted to have interfaces in a new namespace that would return HRESULT instead of throwing exceptions for some time now, but it never got to the top of priority list :) Anyway, I've created DbgEngFixes branch, so please take a look if this unblocks you for now :)
https://github.com/southpolenator/WinDbgCs/blob/ce944d6462e6a215aeef982a98ceced25171595f/Source/CsDebugScript.DbgEng/DbgEng/NoExceptions/IDebugControl.cs#L500
Once I have more time, I'll fix uints to be mapped to enums, documentation, etc.

On the other hand, I'm not sure what is your scenario, but if others can benefit from it, please do share it, maybe it can become part of this library :) Also, if other debuggers can support what you are doing, then it makes even more sense to add support for it :)

**Comment by southpolenator** [comment]
Fixed.
